# base
seed: 0
deterministic: True

# environment config
device: cpu     # examples: [0], cpu, mps, not supported DDP 

# project config
project: outputs/GCN
name: cora

# model config
hidden_dim: 256
dropout: 0.1
directed: False                          # if True, directed graph will be constructed.
dynamic: True                            # if True, [D^-0.5 x A x D^-0.5] will be used to normalize graph or [D^-1 x A] will be used.

# data config
cora_dataset_train: True                 # if True, Cora dataset will be loaded automatically.
cora_dataset:
    path: data/
CUSTOM:
    train_data_path: null
    validation_data_path: null
    test_data_path: null

# train config
epochs: 1000
lr: 1e-2

# logging config
common: ['train_loss', 'train_acc', 'validation_loss', 'validation_acc', 'lr']